#!/bin/sh
mvn clean package && docker build -t 22012/ExamEmployeeClient .
docker rm -f ExamEmployeeClient 2>/dev/null || true && docker run -it --name ExamEmployeeClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ExamEmployeeClient 22012/ExamEmployeeClient
