#!/bin/sh
mvn clean package && docker build -t 22012/TestDepartment .
docker rm -f TestDepartment 2>/dev/null || true && docker run -it --name TestDepartment -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TestDepartment 22012/TestDepartment
