#!/bin/sh
mvn clean package && docker build -t 22012/ReviewCategoryMP .
docker rm -f ReviewCategoryMP 2>/dev/null || true && docker run -it --name ReviewCategoryMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ReviewCategoryMP 22012/ReviewCategoryMP
