#!/bin/sh
mvn clean package && docker build -t 22012/ReviewFrontMP .
docker rm -f ReviewFrontMP 2>/dev/null || true && docker run -it --name ReviewFrontMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ReviewFrontMP 22012/ReviewFrontMP
